### ISSUE TITLE
Update "Set Up External Authentication" document

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/website#2113]
The following document is out of date. Need to be updated.
In the latest Kubepshere 3.2.0 release, we recommend updating the authentication settings through **ClusterConfiguration** ks-installer instead of the **kubesphere-config**.

```
kubectl -n kubesphere-system edit cc ks-installer
```

https://kubesphere.com.cn/docs/access-control-and-account-management/external-authentication/set-up-external-authentication/
https://kubesphere.com.cn/en/docs/access-control-and-account-management/external-authentication/set-up-external-authentication/

**Comment by RolandMa1986** [comment]
@kubesphere/sig-docs

**Comment by Felixnoo** [comment]
@RolandMa1986 
Can you provide more information about how to update the authentication settings through **ClusterConfiguration** ks-installer?

**Comment by RolandMa1986** [comment]
It's almost as same as the origin step. You can either run the `kubectl -n kubesphere-system edit cc ks-installer` command to edit it on the CLI or find it under CRD in console UI to edit the ks-installer configuration.
For example, If you plan to use an LDAP adapter, just as below:

```yaml
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  labels:
    version: v3.2.0
  name: ks-installer
  namespace: kubesphere-system
spec:
  alerting:
    enabled: false
  auditing:
    enabled: false
  authentication:
    jwtSecret: ''
    oauthOptions:
      identityProviders:
        - mappingMethod: auto
          name: LDAP
          provider:
            host: '192.168.1.3:389'
            loginAttribute: uid
            mailAttribute: mail
            managerDN: 'cn=admin,dc=example,dc=org'
            managerPassword: admin
            userSearchBase: 'dc=example,dc=org'
          type: LDAPIdentityProvider
```
